language: python

install:
  # Get all of the dependencies you need
  - pip install -r requirements.txt

before_script:
  # Execute all of the commands which need to be executed
  # before running actual tests
  - python datasource/dataprocess/database.py
  - python manage.py makemigrations user_account
  - python manage.py makemigrations homepage
  - python manage.py migrate
  - python manage.py collectstatic


script:
  # Execute all of the commands which
  # should make the build pass or fail
  - black --check .
  - flake8 .
  - coverage run manage.py test --keepdb


after_script:
  - coveralls