# Generated by Django 2.2.6 on 2019-11-05 01:09

from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_time', models.DateTimeField(default=homepage.models.in_one_day)),
                ('user_request1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrequestmatch_user1', to='homepage.UserRequest')),
                ('user_request2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrequestmatch_user2', to='homepage.UserRequest')),
            ],
        ),
        migrations.DeleteModel(
            name='UserMatch',
        ),
    ]
