# Generated by Django 2.2.5 on 2019-11-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='cuisines_priority',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='department_priority',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='interests_priority',
            field=models.IntegerField(default=10),
        ),
    ]
