# Generated by Django 2.2.6 on 2019-11-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='cuisine',
            field=models.ManyToManyField(blank=True, to='homepage.Cuisine'),
        ),
    ]
