# Generated by Django 2.2.5 on 2019-10-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("homepage", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={"db_table": "cuisine", "managed": False},
        )
    ]
