# Generated by Django 2.2.6 on 2019-11-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("homepage", "0002_auto_20191104_1751")]

    operations = [
        migrations.RenameField(
            model_name="days_left", old_name="user_id", new_name="user"
        )
    ]
