# Generated by Django 2.2.6 on 2019-11-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [("homepage", "0002_auto_20191103_2214")]

    operations = [
        migrations.AlterModelTable(name="cuisine", table=None),
        migrations.AlterModelTable(name="days_left", table=None),
        migrations.AlterModelTable(name="department", table=None),
        migrations.AlterModelTable(name="restaurant", table=None),
        migrations.AlterModelTable(name="school", table=None),
        migrations.AlterModelTable(name="userrequest", table=None),
    ]
