# Generated by Django 2.2.5 on 2019-10-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_userrequest'),
    ]

    operations = [
    ]
