# Generated by Django 2.2.6 on 2019-11-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lunchninjauser',
            old_name='phone',
            new_name='Phone',
        ),
    ]
